"""Full v2 Schema

Revision ID: 516f14ab0642
Revises: 88a7ab910c4b
Create Date: 2025-12-13 20:15:32.165918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516f14ab0642'
down_revision = '88a7ab910c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_machine_code'), ['machine_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('machine_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.BigInteger(), nullable=False),
    sa.Column('machine_user_id', sa.String(), nullable=False),
    sa.Column('machine_user_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_raw_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('machine_user_id_fk', sa.BigInteger(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['machine_user_id_fk'], ['machine_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_nis', sa.String(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_daily_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_daily_student_nis'), ['student_nis'], unique=False)

    op.create_table('student_machine_maps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_user_id_fk', sa.BigInteger(), nullable=False),
    sa.Column('student_nis', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['machine_user_id_fk'], ['machine_users.id'], ),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_user_id_fk')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_student_nis'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('parent_phone')

    op.create_table('attendance_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_nis', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], name=op.f('attendance_records_student_nis_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_records_pkey'))
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_student_nis'), ['student_nis'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_id'), ['id'], unique=False)

    op.drop_table('student_machine_maps')
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_daily_student_nis'))
        batch_op.drop_index(batch_op.f('ix_attendance_daily_id'))

    op.drop_table('attendance_daily')
    op.drop_table('attendance_raw_logs')
    op.drop_table('machine_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_machine_code'))

    op.drop_table('machines')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
