"""Phase 9: Add SystemConfig and SchoolHoliday

Revision ID: 52b28c2b798b
Revises: 16a0632b0678
Create Date: 2025-12-14 18:45:16.820725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b28c2b798b'
down_revision = '16a0632b0678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_holidays_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_school_holidays_id'), ['id'], unique=False)

    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_category'))

    op.drop_table('system_config')
    with op.batch_alter_table('school_holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_holidays_id'))
        batch_op.drop_index(batch_op.f('ix_school_holidays_date'))

    op.drop_table('school_holidays')
    # ### end Alembic commands ###
