"""Change notification_settings to use user_id

Revision ID: 756012dec253
Revises: 558537c8107d
Create Date: 2025-12-14 18:04:39.314320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756012dec253'
down_revision = '558537c8107d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('notification_settings_teacher_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_constraint(batch_op.f('notification_settings_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_settings_teacher_id_fkey'), 'teachers', ['teacher_id'], ['teacher_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('notification_settings_teacher_id_key'), ['teacher_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
