"""Initial migration

Revision ID: 88a7ab910c4b
Revises: 
Create Date: 2025-12-13 18:09:31.852649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a7ab910c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('teacher_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('classes',
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('wali_kelas_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wali_kelas_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_class_id'), ['class_id'], unique=False)

    op.create_table('students',
    sa.Column('nis', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('nis')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_nis'), ['nis'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_nis', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_student_nis'), ['student_nis'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_student_nis'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_nis'))

    op.drop_table('students')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_class_id'))

    op.drop_table('classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_teacher_id'))

    op.drop_table('teachers')
    # ### end Alembic commands ###
