"""Add risk_alerts and risk_history tables

Revision ID: b7cada712990
Revises: e60c3cc4933d
Create Date: 2025-12-14 17:12:26.955250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cada712990'
down_revision = 'e60c3cc4933d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_nis', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('action_notes', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['teachers.teacher_id'], ),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_alerts_student_nis'), ['student_nis'], unique=False)

    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_nis', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_nis'], ['students.nis'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_history_student_nis'), ['student_nis'], unique=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('last_sync')
        batch_op.drop_column('status')

    with op.batch_alter_table('risk_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_history_student_nis'))
        batch_op.drop_index(batch_op.f('ix_risk_history_id'))

    op.drop_table('risk_history')
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_alerts_student_nis'))
        batch_op.drop_index(batch_op.f('ix_risk_alerts_id'))

    op.drop_table('risk_alerts')
    # ### end Alembic commands ###
