"""Add notes and recorded_by to attendance

Revision ID: e60c3cc4933d
Revises: 516f14ab0642
Create Date: 2025-12-13 23:14:36.930937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60c3cc4933d'
down_revision = '516f14ab0642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recorded_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_daily_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_foreign_key(None, 'teachers', ['recorded_by'], ['teacher_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_daily', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendance_daily_attendance_date'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('recorded_by')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
